{"name": "test_failed", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <app.test_docker.TestDocker object at 0x7fdef74f4eb0>\n\n    @allure.story(\"Failed\")\n    def test_failed(self):\n        with allure.step(\"Тестове падіння тесту\"):\n>           assert False\nE           assert False\n\napp/test_docker.py:63: AssertionError"}, "steps": [{"name": "Тестове падіння тесту", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n", "trace": "  File \"/app/app/test_docker.py\", line 63, in test_failed\n    assert False\n"}, "start": 1753448826265, "stop": 1753448826265}], "start": 1753448826265, "stop": 1753448826266, "uuid": "52ebdff5-2a93-4a97-8b38-0f21460e72ff", "historyId": "5b9a584cf7fd411f67a1a02ae66b1ecf", "testCaseId": "5b9a584cf7fd411f67a1a02ae66b1ecf", "fullName": "app.test_docker.TestDocker#test_failed", "labels": [{"name": "feature", "value": "DB Docker"}, {"name": "story", "value": "Failed"}, {"name": "parentSuite", "value": "app"}, {"name": "suite", "value": "test_docker"}, {"name": "subSuite", "value": "TestDocker"}, {"name": "host", "value": "3e2f3d9f9235"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "app.test_docker"}], "titlePath": ["app", "test_docker.py", "TestDocker"]}